---
- name: Install kubectl
  when: ansible_local["bin"]["kubectl"] != kubectl_version
  block:
    - name: Download kubectl "{{ kubectl_version }}" for "{{ ansible_local.host.arch.package }}"
      get_url:
        url: https://dl.k8s.io/release/v{{ kubectl_version }}/bin/linux/{{ ansible_local.host.arch.package }}/kubectl
        dest: /var/ansible/tmp/kubectl

    - name: Install kubectl
      become: yes
      become_user: root
      shell: |
        rm /usr/local/bin/kubectl || true; \
        install --group root --mode 755 --owner root /var/ansible/tmp/kubectl /usr/local/bin \
        && rm /var/ansible/tmp/kubectl

    - name: Bash completion for kubectl
      become: yes
      become_user: root
      shell: |
        kubectl completion "$(basename "${SHELL}")" > /etc/bash_completion.d/kubectl
