---
- name: Mount the NAS
  when: ansible_local["nas"]["source"] == ""
  block:
    - name: Create a directory if it does not exist
      become: yes
      become_user: root
      ansible.builtin.file:
        path: /mnt/nas
        state: directory
        mode: "0777"

    - name: Install dependencies
      become: yes
      become_user: root
      apt:
        name:
          - nfs-common
        state: present

    - name: Mount NAS
      become: yes
      become_user: root
      ansible.posix.mount:
        src: 192.168.72.10:/volume1/cluster
        path: /mnt/nas
        opts: x-systemd.automount
        state: mounted
        fstype: nfs

    - name: Reload daemon
      when: ansible_local["cluster"]["registry"] == ""
      shell: |
        systemctl daemon-reload
        systemctl restart remote-fs.target
        systemctl restart local-fs.target
